// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// JobInfoRequest defines required input for retrieving job-related information.
type JobInfoRequest struct {
	Jid                  string   `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Xml                  bool     `protobuf:"varint,2,opt,name=xml,proto3" json:"xml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobInfoRequest) Reset()         { *m = JobInfoRequest{} }
func (m *JobInfoRequest) String() string { return proto.CompactTextString(m) }
func (*JobInfoRequest) ProtoMessage()    {}
func (*JobInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a3b9062f980bef7b, []int{0}
}
func (m *JobInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobInfoRequest.Unmarshal(m, b)
}
func (m *JobInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobInfoRequest.Marshal(b, m, deterministic)
}
func (dst *JobInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobInfoRequest.Merge(dst, src)
}
func (m *JobInfoRequest) XXX_Size() int {
	return xxx_messageInfo_JobInfoRequest.Size(m)
}
func (m *JobInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobInfoRequest proto.InternalMessageInfo

func (m *JobInfoRequest) GetJid() string {
	if m != nil {
		return m.Jid
	}
	return ""
}

func (m *JobInfoRequest) GetXml() bool {
	if m != nil {
		return m.Xml
	}
	return false
}

// UserInfoRequest defines required input for retrieving user-related information.
type UserInfoRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Xml                  bool     `protobuf:"varint,2,opt,name=xml,proto3" json:"xml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a3b9062f980bef7b, []int{1}
}
func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (dst *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(dst, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserInfoRequest) GetXml() bool {
	if m != nil {
		return m.Xml
	}
	return false
}

// GeneralResponse is a very simple and naive output message.
type GeneralResponse struct {
	ResponseData         string   `protobuf:"bytes,1,opt,name=responseData,proto3" json:"responseData,omitempty"`
	ExitCode             int32    `protobuf:"varint,2,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralResponse) Reset()         { *m = GeneralResponse{} }
func (m *GeneralResponse) String() string { return proto.CompactTextString(m) }
func (*GeneralResponse) ProtoMessage()    {}
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a3b9062f980bef7b, []int{2}
}
func (m *GeneralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralResponse.Unmarshal(m, b)
}
func (m *GeneralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralResponse.Marshal(b, m, deterministic)
}
func (dst *GeneralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralResponse.Merge(dst, src)
}
func (m *GeneralResponse) XXX_Size() int {
	return xxx_messageInfo_GeneralResponse.Size(m)
}
func (m *GeneralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralResponse proto.InternalMessageInfo

func (m *GeneralResponse) GetResponseData() string {
	if m != nil {
		return m.ResponseData
	}
	return ""
}

func (m *GeneralResponse) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *GeneralResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*JobInfoRequest)(nil), "grpc.JobInfoRequest")
	proto.RegisterType((*UserInfoRequest)(nil), "grpc.UserInfoRequest")
	proto.RegisterType((*GeneralResponse)(nil), "grpc.GeneralResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TorqueHelperSrvServiceClient is the client API for TorqueHelperSrvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TorqueHelperSrvServiceClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GeneralResponse, error)
	TraceJob(ctx context.Context, in *JobInfoRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	TorqueConfig(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GeneralResponse, error)
	MoabConfig(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GeneralResponse, error)
	GetJobBlockReason(ctx context.Context, in *JobInfoRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	GetBlockedJobsOfUser(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	Qstat(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GeneralResponse, error)
	Qstatx(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GeneralResponse, error)
}

type torqueHelperSrvServiceClient struct {
	cc *grpc.ClientConn
}

func NewTorqueHelperSrvServiceClient(cc *grpc.ClientConn) TorqueHelperSrvServiceClient {
	return &torqueHelperSrvServiceClient{cc}
}

func (c *torqueHelperSrvServiceClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/grpc.TorqueHelperSrvService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torqueHelperSrvServiceClient) TraceJob(ctx context.Context, in *JobInfoRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/grpc.TorqueHelperSrvService/TraceJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torqueHelperSrvServiceClient) TorqueConfig(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/grpc.TorqueHelperSrvService/TorqueConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torqueHelperSrvServiceClient) MoabConfig(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/grpc.TorqueHelperSrvService/MoabConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torqueHelperSrvServiceClient) GetJobBlockReason(ctx context.Context, in *JobInfoRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/grpc.TorqueHelperSrvService/GetJobBlockReason", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torqueHelperSrvServiceClient) GetBlockedJobsOfUser(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/grpc.TorqueHelperSrvService/GetBlockedJobsOfUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torqueHelperSrvServiceClient) Qstat(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/grpc.TorqueHelperSrvService/Qstat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torqueHelperSrvServiceClient) Qstatx(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/grpc.TorqueHelperSrvService/Qstatx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TorqueHelperSrvServiceServer is the server API for TorqueHelperSrvService service.
type TorqueHelperSrvServiceServer interface {
	Ping(context.Context, *empty.Empty) (*GeneralResponse, error)
	TraceJob(context.Context, *JobInfoRequest) (*GeneralResponse, error)
	TorqueConfig(context.Context, *empty.Empty) (*GeneralResponse, error)
	MoabConfig(context.Context, *empty.Empty) (*GeneralResponse, error)
	GetJobBlockReason(context.Context, *JobInfoRequest) (*GeneralResponse, error)
	GetBlockedJobsOfUser(context.Context, *UserInfoRequest) (*GeneralResponse, error)
	Qstat(context.Context, *empty.Empty) (*GeneralResponse, error)
	Qstatx(context.Context, *empty.Empty) (*GeneralResponse, error)
}

func RegisterTorqueHelperSrvServiceServer(s *grpc.Server, srv TorqueHelperSrvServiceServer) {
	s.RegisterService(&_TorqueHelperSrvService_serviceDesc, srv)
}

func _TorqueHelperSrvService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorqueHelperSrvServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TorqueHelperSrvService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorqueHelperSrvServiceServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorqueHelperSrvService_TraceJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorqueHelperSrvServiceServer).TraceJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TorqueHelperSrvService/TraceJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorqueHelperSrvServiceServer).TraceJob(ctx, req.(*JobInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorqueHelperSrvService_TorqueConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorqueHelperSrvServiceServer).TorqueConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TorqueHelperSrvService/TorqueConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorqueHelperSrvServiceServer).TorqueConfig(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorqueHelperSrvService_MoabConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorqueHelperSrvServiceServer).MoabConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TorqueHelperSrvService/MoabConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorqueHelperSrvServiceServer).MoabConfig(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorqueHelperSrvService_GetJobBlockReason_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorqueHelperSrvServiceServer).GetJobBlockReason(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TorqueHelperSrvService/GetJobBlockReason",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorqueHelperSrvServiceServer).GetJobBlockReason(ctx, req.(*JobInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorqueHelperSrvService_GetBlockedJobsOfUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorqueHelperSrvServiceServer).GetBlockedJobsOfUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TorqueHelperSrvService/GetBlockedJobsOfUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorqueHelperSrvServiceServer).GetBlockedJobsOfUser(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorqueHelperSrvService_Qstat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorqueHelperSrvServiceServer).Qstat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TorqueHelperSrvService/Qstat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorqueHelperSrvServiceServer).Qstat(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorqueHelperSrvService_Qstatx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorqueHelperSrvServiceServer).Qstatx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TorqueHelperSrvService/Qstatx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorqueHelperSrvServiceServer).Qstatx(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _TorqueHelperSrvService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.TorqueHelperSrvService",
	HandlerType: (*TorqueHelperSrvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _TorqueHelperSrvService_Ping_Handler,
		},
		{
			MethodName: "TraceJob",
			Handler:    _TorqueHelperSrvService_TraceJob_Handler,
		},
		{
			MethodName: "TorqueConfig",
			Handler:    _TorqueHelperSrvService_TorqueConfig_Handler,
		},
		{
			MethodName: "MoabConfig",
			Handler:    _TorqueHelperSrvService_MoabConfig_Handler,
		},
		{
			MethodName: "GetJobBlockReason",
			Handler:    _TorqueHelperSrvService_GetJobBlockReason_Handler,
		},
		{
			MethodName: "GetBlockedJobsOfUser",
			Handler:    _TorqueHelperSrvService_GetBlockedJobsOfUser_Handler,
		},
		{
			MethodName: "Qstat",
			Handler:    _TorqueHelperSrvService_Qstat_Handler,
		},
		{
			MethodName: "Qstatx",
			Handler:    _TorqueHelperSrvService_Qstatx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}

// TorqueHelperMomServiceClient is the client API for TorqueHelperMomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TorqueHelperMomServiceClient interface {
	JobMemInfo(ctx context.Context, in *JobInfoRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
}

type torqueHelperMomServiceClient struct {
	cc *grpc.ClientConn
}

func NewTorqueHelperMomServiceClient(cc *grpc.ClientConn) TorqueHelperMomServiceClient {
	return &torqueHelperMomServiceClient{cc}
}

func (c *torqueHelperMomServiceClient) JobMemInfo(ctx context.Context, in *JobInfoRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/grpc.TorqueHelperMomService/JobMemInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TorqueHelperMomServiceServer is the server API for TorqueHelperMomService service.
type TorqueHelperMomServiceServer interface {
	JobMemInfo(context.Context, *JobInfoRequest) (*GeneralResponse, error)
}

func RegisterTorqueHelperMomServiceServer(s *grpc.Server, srv TorqueHelperMomServiceServer) {
	s.RegisterService(&_TorqueHelperMomService_serviceDesc, srv)
}

func _TorqueHelperMomService_JobMemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorqueHelperMomServiceServer).JobMemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TorqueHelperMomService/JobMemInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorqueHelperMomServiceServer).JobMemInfo(ctx, req.(*JobInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TorqueHelperMomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.TorqueHelperMomService",
	HandlerType: (*TorqueHelperMomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JobMemInfo",
			Handler:    _TorqueHelperMomService_JobMemInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_grpc_a3b9062f980bef7b) }

var fileDescriptor_grpc_a3b9062f980bef7b = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x5f, 0x8b, 0xda, 0x40,
	0x14, 0xc5, 0xb1, 0xfe, 0xc1, 0x5e, 0xa4, 0xb6, 0x83, 0x15, 0xb1, 0x2f, 0xe2, 0x93, 0x4f, 0x11,
	0x6c, 0x6d, 0x29, 0xa5, 0x50, 0xaa, 0xc5, 0x6e, 0x20, 0xec, 0x6e, 0x74, 0x3f, 0xc0, 0x4c, 0xbc,
	0x09, 0xd9, 0x4d, 0x72, 0xe3, 0xcc, 0x44, 0xdc, 0x0f, 0xbf, 0xb0, 0x4c, 0xa2, 0xbb, 0xab, 0xac,
	0x0f, 0xd9, 0xb7, 0x33, 0x87, 0xfb, 0x9b, 0x39, 0x9c, 0xb9, 0x00, 0x81, 0x4c, 0x3d, 0x2b, 0x95,
	0xa4, 0x89, 0xd5, 0x8c, 0xee, 0x7f, 0x09, 0x88, 0x82, 0x08, 0xc7, 0xb9, 0x27, 0x32, 0x7f, 0x8c,
	0x71, 0xaa, 0xef, 0x8b, 0x91, 0xe1, 0x37, 0xf8, 0x60, 0x93, 0xb8, 0x48, 0x7c, 0x72, 0x71, 0x93,
	0xa1, 0xd2, 0xec, 0x23, 0x54, 0x6f, 0xc3, 0x75, 0xaf, 0x32, 0xa8, 0x8c, 0xde, 0xbb, 0x46, 0x1a,
	0x67, 0x17, 0x47, 0xbd, 0x77, 0x83, 0xca, 0xa8, 0xe9, 0x1a, 0x39, 0x9c, 0x42, 0xfb, 0x46, 0xa1,
	0x3c, 0xc1, 0xb2, 0x67, 0x2c, 0x7b, 0x15, 0xcb, 0xa0, 0xbd, 0xc0, 0x04, 0x25, 0x8f, 0x5c, 0x54,
	0x29, 0x25, 0x0a, 0xd9, 0x10, 0x5a, 0x72, 0xaf, 0xe7, 0x5c, 0xf3, 0x3d, 0x7f, 0xe4, 0xb1, 0x3e,
	0x34, 0x71, 0x17, 0xea, 0x19, 0xad, 0x31, 0xbf, 0xad, 0xee, 0x3e, 0x9d, 0x0d, 0x8f, 0x52, 0x92,
	0x74, 0x50, 0x29, 0x1e, 0x60, 0xaf, 0x5a, 0xf0, 0x2f, 0xbd, 0xc9, 0x43, 0x15, 0xba, 0x2b, 0x92,
	0x9b, 0x0c, 0xff, 0x63, 0x94, 0xa2, 0x5c, 0xca, 0xed, 0x12, 0xe5, 0x36, 0xf4, 0x90, 0x4d, 0xa1,
	0x76, 0x15, 0x26, 0x01, 0xeb, 0x5a, 0x45, 0x49, 0xd6, 0xa1, 0x24, 0xeb, 0x9f, 0x29, 0xa9, 0xff,
	0xd9, 0xca, 0xeb, 0x3c, 0x4d, 0xfd, 0x03, 0x9a, 0x2b, 0xc9, 0x3d, 0xb4, 0x49, 0xb0, 0x4e, 0x31,
	0x72, 0xdc, 0xe2, 0x39, 0xf0, 0x37, 0xb4, 0x8a, 0x24, 0x33, 0x4a, 0xfc, 0xb0, 0xf4, 0xbb, 0xbf,
	0x00, 0x1c, 0xe2, 0xe2, 0x6d, 0xf0, 0x1f, 0xf8, 0xb4, 0x40, 0x6d, 0x93, 0xf8, 0x1b, 0x91, 0x77,
	0xe7, 0x22, 0x57, 0x94, 0x94, 0x4b, 0x3f, 0x87, 0xce, 0x02, 0x75, 0x8e, 0xe3, 0xda, 0x26, 0xa1,
	0x2e, 0x7d, 0xb3, 0x06, 0x6c, 0x3f, 0x7e, 0xb2, 0x12, 0xe7, 0x6e, 0xf9, 0x0e, 0xf5, 0x6b, 0xa5,
	0xb9, 0x2e, 0x5f, 0x7a, 0x23, 0xe7, 0x76, 0x25, 0xc1, 0xc9, 0xf2, 0xf8, 0xfb, 0x1d, 0x8a, 0x0f,
	0xdf, 0xff, 0x13, 0xc0, 0x26, 0xe1, 0x60, 0x6c, 0x62, 0x97, 0xea, 0x42, 0x34, 0xf2, 0xb7, 0xbf,
	0x3e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x37, 0x0d, 0xf2, 0x87, 0x70, 0x03, 0x00, 0x00,
}
