###############################################################################
# This is an ansible playbook for deploying RPMs onto various servers on the
# HPC cluster at DCCN.
#
# use command:
#
#     $ ansible-playbook ansible.yml -K
#
###############################################################################
- name: set version number
  gather_facts: false
  hosts:
    - pbs_server
    - pbs_mom
    - mentat
  vars_prompt:
    - name: rel_version
      prompt: RPM version to deply
      default: 1.2.1-1.el7.x86_64
      private: no
  tasks:
    # global facts
    - name: "rel_version: {{rel_version}}"
      set_fact:
        repodir: "/mnt/install/kickstart-7/miscpkgs/torque-helper"
        release: "{{rel_version}}"
    # group-specific facts
    - name: "set pkg name for SRV component"
      set_fact:
        pkg_name: hpc-torque-helper-server-srv
      when: "'pbs_server' in group_names"
    - name: "set pkg name for MOM component"
      set_fact:
        pkg_name: hpc-torque-helper-server-mom
      when: "'pbs_mom' in group_names"
    - name: "set pkg name for ACC component"
      set_fact:
        pkg_name: hpc-torque-helper-server-acc
      when: "'mentat' in group_names"

- hosts: pbs_server:pbs_mom:mentat
  gather_facts: false
  become: yes
  vars:
    rpmpath: "{{repodir}}/{{pkg_name}}-{{ release | mandatory }}.rpm"
  tasks:
    - name: check RPM file on nodes
      stat:
        path: "{{rpmpath}}"
      register: rpmfile
    - name: fail on RPM file not available
      fail:
        msg: "rpm not found: {{rpmpath}}"
      when: rpmfile.stat.exists == False
    - name: install/update hpc-torque-helper
      register: yum
      yum:
        name: "{{rpmpath}}"
        state: present